// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenturaHR.Infrastructure.Data;

#nullable disable

namespace VenturaHR.Infrastructure.Migrations
{
    [DbContext(typeof(VenturaDbContext))]
    partial class VenturaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("VenturaHR.Domain.Entities.Resposta.Resposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Indice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RespostaData")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VagaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("VagaId");

                    b.ToTable("Respostas");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Resposta.RespostaCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RespostaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RespostaId");

                    b.ToTable("RespostaCriterios");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<int>("Tipo").HasValue(1);
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Vaga.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cargo")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("FormaContratacao")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Vagas");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Vaga.VagaCriterio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.Property<int>("VagaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VagaId");

                    b.ToTable("VagaCriterios");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Administrador", b =>
                {
                    b.HasBaseType("VenturaHR.Domain.Entities.Usuario.Usuario");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Candidato", b =>
                {
                    b.HasBaseType("VenturaHR.Domain.Entities.Usuario.Usuario");

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Empresa", b =>
                {
                    b.HasBaseType("VenturaHR.Domain.Entities.Usuario.Usuario");

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Resposta.Resposta", b =>
                {
                    b.HasOne("VenturaHR.Domain.Entities.Usuario.Candidato", "Candidato")
                        .WithMany("Respostas")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VenturaHR.Domain.Entities.Vaga.Vaga", null)
                        .WithMany("Respostas")
                        .HasForeignKey("VagaId");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Resposta.RespostaCriterio", b =>
                {
                    b.HasOne("VenturaHR.Domain.Entities.Resposta.Resposta", "Resposta")
                        .WithMany("Criterios")
                        .HasForeignKey("RespostaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resposta");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Vaga.Vaga", b =>
                {
                    b.HasOne("VenturaHR.Domain.Entities.Usuario.Empresa", "Empresa")
                        .WithMany("Vagas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Vaga.VagaCriterio", b =>
                {
                    b.HasOne("VenturaHR.Domain.Entities.Vaga.Vaga", "Vaga")
                        .WithMany("Criterios")
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vaga");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Resposta.Resposta", b =>
                {
                    b.Navigation("Criterios");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Vaga.Vaga", b =>
                {
                    b.Navigation("Criterios");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Candidato", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("VenturaHR.Domain.Entities.Usuario.Empresa", b =>
                {
                    b.Navigation("Vagas");
                });
#pragma warning restore 612, 618
        }
    }
}
